stages:
  - static-analysis
  - build
  - scan
  - push

.common:
  tags:
    - docker
  except: 
    refs:
      - flux-sync

.docker-template:
  extends: .common
  image:
    name: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:  
    - echo -n $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin
  after_script:
    - docker logout

.static-analysis:common:
  extends: .common
  image:
    name: github/super-linter:latest
  stage: static-analysis
  allow_failure: true
  variables:
    RUN_LOCAL: "true"
  only:
    changes:
      - src/$SERVICE/**/*
  script:
    - echo "Scaning..."

.build:common:
  extends: .docker-template
  stage: build
  only:
    changes:
      - src/$SERVICE/**/*
  script:
    - cd src/$SERVICE
    - docker build . -f Dockerfile -t $CI_REGISTRY_USER/$SERVICE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_USER/$SERVICE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA

.scan:common:
  extends: .common
  stage: scan
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  allow_failure: true
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache curl
    - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - echo $VERSION
    - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
    - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
  only:
    changes:
      - src/$SERVICE/**/*
  script:
    - ./trivy --exit-code 0 --severity CRITICAL --no-progress $CI_REGISTRY_USER/$SERVICE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA

.push:common:
  extends: .docker-template
  stage: push
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - /^v\d+\.\d+\.\d+/
    changes:
      - src/$SERVICE/**/*
  script:
    - docker pull $CI_REGISTRY_USER/$SERVICE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA
    - docker tag  $CI_REGISTRY_USER/$SERVICE:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA $CI_REGISTRY_USER/$SERVICE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_USER/$SERVICE:$CI_COMMIT_TAG

include:
  - '/pipeline/static-analysis.yaml'
  - '/pipeline/build.yaml'
  - '/pipeline/scan.yaml'
  - '/pipeline/push.yaml'