apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.33.254
     iqn: iqn.2003-01.org.linux-iscsi.uiscsi.x8664:sn.d18ce9e73eff
     lun: 0
     fsType: 'ext4'
     readOnly: false